nelmio_api_doc:
    documentation:
        info:
            title: "Epimusic API"
            description: "Documentation de l'API pour Epimusic"
            version: "1.0.0"
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    html_config:
        assets_mode: bundle # Change this according to your needs
        swagger_ui_config: # Config options for Swagger UI
            display_request_duration: true # Example of an option you might use
